version: '2.4'

networks:
  test_proj:
    driver: bridge

volumes:
  database-storage: {}

services:
  database:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test_proj
    volumes:
      - database-storage:/var/lib/postgresql/data
    ports: 
      - 5431:5432
    networks:
      - test_proj
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    command: ["./entrypoint.sh"]
    ports: 
      - 8050:8050
    volumes:
      - .:/code
    links:
      - database
    networks:
      - test_proj
    depends_on:
      database:
        condition: service_healthy